version: "3.8"

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=database
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "jeanpi3rm@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "31416"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  spring-app:
    image: jeanpierm/rest-api-spring-boot:latest
    build:
      context: . # Dockerfile on the same directory
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/database
    depends_on:
      - postgres

volumes:
  database-data: # named volumes can be managed easier using docker-compose
  pgadmin:
