### LOGIN USER

POST http://localhost:8080/api/login
content-type: application/json

{
  "username": "jeanpierm",
  "password": "314159"
}

### LOGIN USER bad

POST http://localhost:8080/api/login

{
  "username": "jeanpierms",
  "password": "12345"
}
